version: 2
updates:
  - package-ecosystem: composer
    directory: /plugins/my-plugin
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /plugins/my-plugin
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
